config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :profiles
  resources :events
  resources :attendances
  
  post "events/subscribe/:id", to: "subscribes#create", as: "subscribes"
  get "events/subscribe/:id", to: "subscribes#free_subscribe", as: "free_subscribe" 
 
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create_commit :welcome_event_send
 
    belongs_to :user
    belongs_to :event

    def welcome_event_send
        UserMailer.welcome_event_email(self.event, self.user).deliver_now
    end 
end

app/models/event.rb
class Event < ApplicationRecord
    # scope :administrator, -> { where(admin: current_user.id ) }
      
    validates :title, presence: true, length: { in: 4..140 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price,
      presence: true,
      numericality: {
        greater_than_or_equal_to: 0,
        less_than: 1000
      }
    validates :location, presence: true
    validates :duration, presence: true
    validate :is_multiple_of_5
    validates :start_date, presence: true
    validate :date_passed

    has_many :attendances
    has_many :users, through: :attendances

    def end_date
        start_date + duration * 60
    end

    def participale?(user)
        users.include?(user)
    end

    def is_free?
        price == 0
    end

    private
    
    def date_passed
        if start_date.present? && start_date < Date.today
          errors.add(:start_date, "can't be past")
        end
    end

    def is_multiple_of_5
        errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0 
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user

    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    def check_privileges!
        redirect_to root_path, notice: "You dont have enough permissions" unless current_user == Profile.find(params[:id]).user
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :init_profile
  after_create :welcome_send

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :attendances
  has_many :events, through: :attendances

  def init_profile
    self.create_profile!
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    def index 
        @event = Event.find(params[:id])
        @attendances = @event.users
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :only_creator, only: [:edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params.merge(admin: current_user.id))
    @event.errors.full_messages
    if @event.save
    
    redirect_to event_path(id: @event)
    else
    render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id]) 
  end

  def update
    @event = Event.find(params[:id])
     if @event.update(event_params) 

      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
		@event.destroy
		redirect_to root_path
  end

  private

  def event_params
     params.require(:event).permit(:start_date, :duration, :description, :title, :price, :location, :admin)
  end

  def only_creator
    event = Event.find(params[:id])
    unless current_user.id == event.admin
      flash[:notice] = "Vous n'êtes pas le créateur de l'évènement => Impossilble de le modifier."
     redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_privileges!, only: [:show]

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create 
    @profile = Profile.new
    if @profile.create(profile_params) 

     redirect_to root_path
   else
     render :new
   end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params) 

     redirect_to root_path
   else
     render :edit
   end
  end

  def destroy 
  end

  private 

  def profile_params 
    params.require(:profile).permit(:first_name, :last_name, :description)
  end

  def check_privileges!
    redirect_to root_path, notice: "You dont have enough permissions" unless current_user == Profile.find(params[:id]).user
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
    def new
    end

    def create  
        @event = Event.find(params[:id])
    
        @amount = @event.price * 100
    
        customer = Stripe::Customer.create({
          email: params[:stripeEmail],
          source: params[:stripeToken],
        })
      
        charge = Stripe::Charge.create({
          customer: customer.id,
          amount: @amount,
          description: 'Eventbite payment',
          currency: 'eur',
        })
    
        # Création d'une participation d'un user à l'évènement
        @attendance = Attendance.create(stripe_customer_id: customer.id, user: current_user, event: @event)
        
        redirect_to event_path(@event.id)
      
        rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to @event
    end

    def free_subscribe
      @event = Event.find(params[:id])
      @attendance = Attendance.create(user: current_user, event: @event)
    
      redirect_to event_path(@event.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/attendances/index.html.erb
<div class="col col-6 mx-auto text-dark">
	<h2 class="mt-3"><%= @event.title %> - Guest list</h2>
    <p><%= link_to "Edit your event", edit_event_path(@event), class: "btn btn-secondary", role: "button" %></p>
	<ul>
		<% @attendances.each do |user| %>
            <div class="card-body">
            <p class="list-group-item">First Name: <%= user.profile.first_name %></p>
            <p class="list-group-item">Last Name: <%= user.profile.last_name %></p>
            <p class="list-group-item">Email: <%= user.email %></p>
            </div>
        <% end %>
	</ul>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br>
        <%= form_for @event, url: event_path(params[:id]), method: :put do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modification de l'évènement:</h1>
                <div class="field">
                <%= f.label :start_date, "Date:"  %><br />
                <%= f.text_field :start_date, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :duration, "Durée:" %><br />
                <%= f.text_field :duration, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :description, "Description:" %><br />
                <%= f.text_area :description, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :title, "Intitulé:" %><br />
                <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :price, "Prix:" %><br />
                <%= f.text_field :price, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :location, "Localité:" %><br />
                <%= f.text_field :location, class: "form-control" %>
                </div>   
                <div class="actions mt-5">
                <p> <%= f.submit "Modifier", class: "btn btn-lg btn-primary btn-block" %> <%= link_to 'Delete the event', event_path(id: @event), method: :delete, data: { confirm: 'Are you sure?' } %> </p>
                </div>                
        <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="album py-5 ">
    <div class="container">
        <div class="row">
            <% @events.each do |event| %>
                <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                        <h5 class="card-title"><%= event.title %></h5>
                        <%= link_to "Go to this Event", event_path(event.id), :class => "btn btn-primary btn-xl text-uppercase js-scroll-trigger"%>
                    </div>
                </div>
            <% end %>
        </div>
    </div>     
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br>
        <%= form_for @event, url: events_path, method: :post do |f| %>
        <%= render partial: "layouts/error", locals: { resource: @event } %>
        <h1 class="h3 mb-3 font-weight-normal text-center">New Event:</h1>
                <div class="field">
                <%= f.label :start_date, "Date:"  %><br />
                <%= f.text_field :start_date, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :duration, "Durée:" %><br />
                <%= f.text_field :duration, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :description, "Description:" %><br />
                <%= f.text_area :description, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :title, "Intitulé:" %><br />
                <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :price, "Prix:" %><br />
                <%= f.text_field :price, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :location, "Localité:" %><br />
                <%= f.text_field :location, class: "form-control" %>
                </div>   
                <div class="actions mt-5">
                <%= f.submit "Créer", class: "btn btn-lg btn-primary btn-block" %>
                </div>                
        <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm" >
            <h1 class="display-4"><%= @event.title %></h1>
            <p class="lead"><%= @event.description %></p>
            <h5 class="card-title">Participation :</h5>
            <p><%= @event.users.count %></p>
            <h5 class="card-title">Created by :</h5>
            <p><%= User.find(@event.admin).profile.full_name%></p>
            <h5 class="card-title">Début de l'évènement:</h5>
            <p><%= @event.start_date.to_formatted_s(:long) %></p>
            <h5 class="card-title">Fin de l'évènement:</h5>
            <p><%= @event.end_date.to_formatted_s(:long) %></p>
            <h5 class="card-title">Location:</h5>
            <p><%= @event.location %></p>
            <h5 class="card-title">Price:</h5>
            <p><%= @event.price %> €</p>
            <% if current_user.id == @event.admin %>
                <%= link_to "Mon espace évènement", attendances_path(id: @event), class: "btn btn-secondary"%>
            <% elsif current_user.id == @event.admin || @event.participale?(current_user) %>
                <%= link_to "Tu participe déjà à l'évènement", class: "btn btn-secondary"%>
            <% elsif @event.is_free? %>
                <%= link_to "Participer à l'évènement", free_subscribe_path(id: @event), class: "btn btn-primary"%>
            <% else %>
                <%= form_tag subscribes_path do %>
                    <article>
                        <% if flash[:error].present? %>
                        <div id="error_explanation">
                            <p><%= flash[:error] %></p>
                        </div>
                        <% end %>
                    </article>
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="Event subscription"
                            data-amount="<%= @event.price * 100 %>"
                            data-currency="eur"
                            data-locale="auto">
                    </script>
                <% end %>
            <% end %>
        </div>
    </div>
</div>   

app/views/layouts/_error.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" role="alert" id="error_explanation">
    <h5><%= pluralize(resource.errors.count, "error") %> prohibited this article from being saved:</h5>
 
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "EVENTBRITE", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <%= link_to "Create Event", new_event_path, class: "btn btn-primary" %>  
    </div>
    <% if current_user %> 
        <%= link_to "Profile", profile_path(current_user.profile), class: "btn btn-outline-primary space_left_button" %> 
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary space_left_button" %>
    <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-primary space_left_button" %>
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-primary space_left_button" %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite2020</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CDN -->
  <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/litera/bootstrap.min.css" rel="stylesheet" integrity="sha384-pLgJ8jZ4aoPja/9zBSujjzs7QbkTKvKw1+zfKuumQF9U+TH3xv09UUsRI52fS+A6" crossorigin="anonymous">    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <div class='alert alert-success p-2'>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class='alert alert-danger p-2'>
        <%= alert %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br>
        <%= form_for @profile, url: profile_path(params[:id]), method: :put do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Edit your profile infos:</h1>
                <div class="field">
                <%= f.label :first_name  %><br />
                <%= f.text_field :first_name, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :last_name %><br />
                <%= f.text_field :last_name, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :description, "Description:" %><br />
                <%= f.text_area :description, class: "form-control" %>
                </div>  
                <div class="actions mt-5">
                <p> <%= f.submit "edit", class: "btn btn-lg btn-primary btn-block" %> </p>
                </div>                
        <% end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/profiles/show.html.erb
<h1 class="display-4">Your profile</h1>
<div class="col-4">
  <h5 class="card-title">E-mail:</h5>
  <p class="card-text"><%= current_user.email %></p><p><%= link_to "Edit email/password", edit_user_registration_path, :class => "btn btn-secondary btn-xl text-uppercase js-scroll-trigger"%></p>
</div> 
<div class="card w-100">
  <div class="card-body">
    <h5 class="card-title">First name:</h5>
    <p class="card-text"><%= @profile.first_name %></p>
    <h5 class="card-title">Last name:</h5>
    <p class="card-text"><%= @profile.last_name %></p>
    <h5 class="card-title">Description:</h5>
    <p class="card-text"><%= @profile.description %></p>
    <%= link_to "Edit your profile infos", edit_profile_path(@profile), :class => "btn btn-secondary btn-xl text-uppercase js-scroll-trigger"%>
  </div>
</div>
<h1 class="display-4">Your Events</h1>
<ul class="list-group">
  <% current_user.events.where(admin: current_user.id).each do |event| %>

    <li class="list-group-item">
      <%= event.title %>
      <%= link_to "Go to this Event", event_path(event.id), :class => "btn btn-primary btn-xl text-uppercase js-scroll-trigger"%>
    </li>
  <% end %>
</ul>